##  -*- python -*-  
# db file automatically generated by genconf on: Tue Jun 13 15:01:33 2017
## insulates outside world against anything bad that could happen
## also prevents global scope pollution
def _fillCfgDb():
    from GaudiKernel.Proxy.ConfigurableDb import CfgDb

    # get a handle on the repository of Configurables
    cfgDb = CfgDb()

    # populate the repository with informations on Configurables 

    cfgDb.add( configurable = 'ZeeDLauncher',
               package = 'ZeeDAnalysis',
               module  = 'ZeeDAnalysis.ZeeDAnalysisConf',
               lib     = 'ZeeDAnalysis' )
    cfgDb.add( configurable = 'ZeeDPlotter',
               package = 'ZeeDAnalysis',
               module  = 'ZeeDAnalysis.ZeeDAnalysisConf',
               lib     = 'ZeeDAnalysis' )
    return #_fillCfgDb
# fill cfgDb at module import...
try:
    _fillCfgDb()
    #house cleaning...
    del _fillCfgDb
except Exception,err:
    print "Py:ConfigurableDb   ERROR Problem with [%s] content!" % __name__
    print "Py:ConfigurableDb   ERROR",err
    print "Py:ConfigurableDb   ERROR   ==> culprit is package [ZeeDAnalysis] !"
